/**
 * LeadChatWidget — free-form AI chat for Jobbidder.io (v4)
 *
 * v4: rebuilt around one rule — the user types whatever they want, and gets a
 * real answer back from Claude. No canned quick-reply buttons putting words
 * in their mouth, no proactive unprompted pop-ups, no rigid name/email/issue
 * script that hijacks the input box. Lead capture and support escalation
 * still work, but as a silent background side effect of normal conversation:
 * the assistant asks for a name/email in its own reply (in the user's
 * language, generated by Claude), the user types it in the same box like any
 * other message, and we quietly file the ticket/lead once we spot an email.
 *
 * A2P compliance note: this widget does NOT collect phone numbers.
 * The GHL LeadConnector widget in <head> handles A2P verification.
 */
import * as React from "react";
import { useState, useEffect, useRef, useCallback } from "react";
import {
  MessageCircle,
  X,
  Send,
  Loader2,
  ChevronDown,
  AlertCircle,
  CheckCircle2,
  ExternalLink,
  ThumbsUp,
  ThumbsDown,
  RotateCcw,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

type Role = "user" | "assistant";

interface Message {
  id: string;
  role: Role;
  text: string;
  ctaLink?: { label: string; href: string };
  isError?: boolean;
  showSatisfaction?: boolean;
}

interface ApiResponse {
  reply: string;
  intent: string;
  escalate: boolean;
  captureLeadBefore?: boolean;
  ctaLink?: { label: string; href: string };
  detectedLanguage?: string;
}

type PendingCapture = { kind: "escalation" | "lead"; issueText: string; pendingHref?: string } | null;

// ─── Multilingual strings ─────────────────────────────────────────────────────

const I18N: Record<string, Record<string, string>> = {
  en: {
    welcome: "Hi! I'm the Jobbidder AI. Ask me anything — proposals, pricing, applying as a contractor, whatever you need.",
    placeholder_default: "Ask me anything…",
    satisfaction_prompt: "Was this helpful?",
    satisfaction_yes: "👍 Yes",
    satisfaction_no: "👎 Not really",
    satisfaction_thanks: "Thanks for the feedback! Anything else I can help with?",
    satisfaction_sorry: "Sorry to hear that. Want me to connect you with our team?",
    powered_by: "Powered by Jobbidder AI · By chatting you agree to our",
    terms: "Terms",
    header_subtitle: "Ask me anything",
    ticket_submitted: "Got it — our team will follow up",
    new_conversation: "New conversation",
    online: "Online",
    offline: "Away",
    error_fallback: "I'm having trouble connecting right now. Please try again or call us at (310) 987-4997.",
  },
  es: {
    welcome: "¡Hola! Soy el AI de Jobbidder. Pregúntame lo que quieras — propuestas, precios, aplicar como contratista, lo que necesites.",
    placeholder_default: "Pregúntame lo que sea…",
    satisfaction_prompt: "¿Fue útil esta conversación?",
    satisfaction_yes: "👍 Sí",
    satisfaction_no: "👎 No mucho",
    satisfaction_thanks: "¡Gracias por tu opinión! ¿Hay algo más en que pueda ayudarte?",
    satisfaction_sorry: "Lo siento. ¿Te gustaría que te conecte con nuestro equipo?",
    powered_by: "Desarrollado por Jobbidder AI · Al chatear aceptas nuestros",
    terms: "Términos",
    header_subtitle: "Pregúntame lo que sea",
    ticket_submitted: "Listo — nuestro equipo te contactará",
    new_conversation: "Nueva conversación",
    online: "En línea",
    offline: "No disponible",
    error_fallback: "Tengo problemas para conectarme ahora mismo. Por favor intenta de nuevo o llámanos al (310) 987-4997.",
  },
  fr: {
    welcome: "Bonjour! Je suis l'IA Jobbidder. Posez-moi n'importe quelle question — devis, tarifs, postuler comme entrepreneur, ce dont vous avez besoin.",
    placeholder_default: "Posez-moi n'importe quelle question…",
    satisfaction_prompt: "Cette conversation vous a-t-elle été utile?",
    satisfaction_yes: "👍 Oui",
    satisfaction_no: "👎 Pas vraiment",
    satisfaction_thanks: "Merci pour votre retour! Puis-je vous aider avec autre chose?",
    satisfaction_sorry: "Je suis désolé. Souhaitez-vous que je vous mette en contact avec notre équipe?",
    powered_by: "Propulsé par Jobbidder AI · En chattant vous acceptez nos",
    terms: "Conditions",
    header_subtitle: "Posez-moi n'importe quelle question",
    ticket_submitted: "C'est noté — notre équipe vous contactera",
    new_conversation: "Nouvelle conversation",
    online: "En ligne",
    offline: "Absent",
    error_fallback: "J'ai du mal à me connecter en ce moment. Veuillez réessayer ou appelez-nous au (310) 987-4997.",
  },
  pt: {
    welcome: "Olá! Sou o AI do Jobbidder. Pergunte-me qualquer coisa — propostas, preços, candidatar-se como contratante, o que precisar.",
    placeholder_default: "Pergunte-me qualquer coisa…",
    satisfaction_prompt: "Esta conversa foi útil?",
    satisfaction_yes: "👍 Sim",
    satisfaction_no: "👎 Não muito",
    satisfaction_thanks: "Obrigado pelo feedback! Posso ajudá-lo com mais alguma coisa?",
    satisfaction_sorry: "Lamento ouvir isso. Gostaria que eu o colocasse em contato com nossa equipe?",
    powered_by: "Desenvolvido por Jobbidder AI · Ao conversar você concorda com nossos",
    terms: "Termos",
    header_subtitle: "Pergunte-me qualquer coisa",
    ticket_submitted: "Combinado — nossa equipe vai te contatar",
    new_conversation: "Nova conversa",
    online: "Online",
    offline: "Ausente",
    error_fallback: "Estou com problemas de conexão agora. Por favor tente novamente ou ligue para (310) 987-4997.",
  },
  ht: {
    welcome: "Bonjou! Mwen se AI Jobbidder. Mande m nenpòt bagay — pwopozisyon, pri, aplike kòm kontraktè, nenpòt sa ou bezwen.",
    placeholder_default: "Mande m nenpòt bagay…",
    satisfaction_prompt: "Èske konvèsasyon sa a te itil?",
    satisfaction_yes: "👍 Wi",
    satisfaction_no: "👎 Pa vrèman",
    satisfaction_thanks: "Mèsi pou fidbak ou! Eske gen lòt bagay mwen ka ede ou?",
    satisfaction_sorry: "Dezole pou tande sa. Èske ou ta renmen mwen mete ou an kontak ak ekip nou an?",
    powered_by: "Alimenté pa Jobbidder AI · An bavardant ou dakò ak",
    terms: "Tèm",
    header_subtitle: "Mande m nenpòt bagay",
    ticket_submitted: "Konprann — ekip nou an pral kontakte ou",
    new_conversation: "Nouvo konvèsasyon",
    online: "Anliy",
    offline: "Pa disponib",
    error_fallback: "Mwen gen pwoblèm koneksyon kounye a. Tanpri eseye ankò oswa rele nou nan (310) 987-4997.",
  },
};

function t(lang: string, key: string): string {
  const strings = I18N[lang] || I18N.en;
  return strings[key] ?? I18N.en[key] ?? key;
}

// ─── Language detection (expanded patterns) ───────────────────────────────────

function detectLangFromText(text: string): string {
  const lower = text.toLowerCase();
  if (/\b(hola|gracias|cómo|como|qué|que|necesito|soy|tengo|quiero|también|tambien|español|precio|contratista|buenos|días|dias|buenas|tardes|noches|ayuda|quiero|puedo|puede|cuánto|cuanto|cuál|cual)\b/.test(lower)) return "es";
  if (/\b(bonjour|merci|comment|je suis|j'ai|j'ai|je veux|aussi|français|francais|entrepreneur|devis|tarif|bonsoir|salut|oui|non|est-ce|qu'est|quel|quelle|combien|puis-je|pouvez|voulez|avez|nous|vous|ils|elles|mon|ma|mes|votre|vos|leur|leurs|avec|pour|dans|sur|par|mais|donc|car|parce|quand|comment|pourquoi|qui|que|quoi)\b/.test(lower)) return "fr";
  if (/\b(olá|ola|obrigado|obrigada|como|eu sou|tenho|quero|também|tambem|português|portugues|contratante|preço|preco|bom dia|boa tarde|boa noite|sim|não|nao|pode|posso|qual|quanto|onde|quando|porque|para|com|mas|ou|se|que|uma|um|são|sao|está|esta|tem|ter|ser|fazer|ir|vir)\b/.test(lower)) return "pt";
  if (/\b(bonjou|mèsi|mesi|kijan|mwen|genyen|vle|kreyòl|kreyol|ayisyen|kontraktè|kontrakте|pri|bonswa|wi|non|ka|pou|nan|ak|ou|li|nou|yo|sa|ki|kote|kilè|poukisa|konbyen|eske|men|avèk|avek)\b/.test(lower)) return "ht";
  return "en";
}

// ─── Business hours check (9am–6pm PST, Mon–Fri) ─────────────────────────────

function isBusinessHours(): boolean {
  try {
    const now = new Date();
    const pst = new Date(now.toLocaleString("en-US", { timeZone: "America/Los_Angeles" }));
    const day = pst.getDay();
    const hour = pst.getHours();
    return day >= 1 && day <= 5 && hour >= 9 && hour < 18;
  } catch {
    return true;
  }
}

// ─── Strip markdown from Claude replies ──────────────────────────────────────

function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/^#+\s+/gm, "")
    .replace(/^[-*]\s+/gm, "• ")
    .replace(/\[(.+?)\]\((.+?)\)/g, "$1 ($2)")
    .trim();
}

// ─── Parse URLs in text into clickable segments ───────────────────────────────

function parseTextWithLinks(text: string): React.ReactNode[] {
  const urlRegex = /(https?:\/\/[^\s)]+)/g;
  const parts = text.split(urlRegex);
  return parts.map((part, i) => {
    if (urlRegex.test(part)) {
      urlRegex.lastIndex = 0;
      return (
        <a key={i} href={part} target="_blank" rel="noreferrer" className="underline text-primary/80 hover:text-primary break-all">
          {part}
        </a>
      );
    }
    urlRegex.lastIndex = 0;
    return <React.Fragment key={i}>{part}</React.Fragment>;
  });
}

// ─── Best-effort contact extraction from a normal chat message ───────────────

function extractEmail(text: string): string | null {
  const m = text.match(/[^\s@]+@[^\s@]+\.[^\s@]+/);
  return m ? m[0] : null;
}

function extractName(text: string, email: string): string {
  const withoutEmail = text.replace(email, "").replace(/[,:;]/g, " ").replace(/\s+/g, " ").trim();
  return withoutEmail || "Web visitor";
}

// ─── Constants ────────────────────────────────────────────────────────────────

const SESSION_KEY = "jb_chat_session";
const STORAGE_KEY = "jb_chat_messages_v4";
const LANG_KEY = "jb_chat_lang";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function uid(): string {
  return Math.random().toString(36).slice(2, 10);
}

function getSessionId(): string {
  if (typeof window === "undefined") return uid();
  let id = sessionStorage.getItem(SESSION_KEY);
  if (!id) {
    id = uid();
    sessionStorage.setItem(SESSION_KEY, id);
  }
  return id;
}

function loadMessages(): Message[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = sessionStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw);
  } catch {}
  return [];
}

function saveMessages(msgs: Message[]) {
  if (typeof window === "undefined") return;
  try {
    sessionStorage.setItem(STORAGE_KEY, JSON.stringify(msgs.slice(-30)));
  } catch {}
}

function loadLang(): string {
  if (typeof window === "undefined") return "en";
  return sessionStorage.getItem(LANG_KEY) || "en";
}

function saveLang(lang: string) {
  if (typeof window === "undefined") return;
  sessionStorage.setItem(LANG_KEY, lang);
}

function buildWelcomeMessage(lang: string): Message {
  return { id: "welcome", role: "assistant", text: t(lang, "welcome") };
}

// ─── API calls ────────────────────────────────────────────────────────────────

async function submitSupportTicket(data: { name: string; email: string; issue: string; sessionId: string }): Promise<boolean> {
  try {
    const res = await fetch("/api/public/support-ticket", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });
    return res.ok;
  } catch {
    return false;
  }
}

async function submitLead(data: { name: string; email: string; sessionId: string; pageUrl: string }): Promise<boolean> {
  try {
    const res = await fetch("/api/public/leads", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });
    return res.ok;
  } catch {
    return false;
  }
}

// ─── Main Component ───────────────────────────────────────────────────────────

export function LeadChatWidget() {
  const [open, setOpen] = useState(false);
  const [lang, setLang] = useState<string>("en");
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [unread, setUnread] = useState(0);
  const [online, setOnline] = useState(true);
  const [pendingCapture, setPendingCapture] = useState<PendingCapture>(null);
  const [captureConfirmed, setCaptureConfirmed] = useState(false);
  const [satisfactionGiven, setSatisfactionGiven] = useState(false);

  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const sessionId = useRef<string>("");

  // ── Init ────────────────────────────────────────────────────────────────────

  useEffect(() => {
    sessionId.current = getSessionId();
    const savedLang = loadLang();
    setLang(savedLang);
    setOnline(isBusinessHours());

    const saved = loadMessages();
    setMessages(saved.length > 0 ? saved : [buildWelcomeMessage(savedLang)]);
  }, []);

  // ── Scroll ──────────────────────────────────────────────────────────────────

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  // ── Focus input ─────────────────────────────────────────────────────────────

  useEffect(() => {
    if (open) {
      setTimeout(() => inputRef.current?.focus(), 150);
      setUnread(0);
    }
  }, [open]);

  // ── Unread badge ────────────────────────────────────────────────────────────

  useEffect(() => {
    if (!open && messages.length > 1) {
      const lastMsg = messages[messages.length - 1];
      if (lastMsg?.role === "assistant") setUnread((n) => n + 1);
    }
  }, [messages]);

  // ── Persist ─────────────────────────────────────────────────────────────────

  useEffect(() => {
    if (messages.length > 0) saveMessages(messages);
  }, [messages]);

  // ── Helpers ─────────────────────────────────────────────────────────────────

  const addMessage = useCallback((msg: Omit<Message, "id">) => {
    setMessages((prev) => [...prev, { ...msg, id: uid() }]);
  }, []);

  const updateLang = useCallback((newLang: string) => {
    setLang(newLang);
    saveLang(newLang);
    setMessages((prev) => prev.map((m) => (m.id === "welcome" ? { ...m, text: t(newLang, "welcome") } : m)));
  }, []);

  // ── New conversation ─────────────────────────────────────────────────────────

  const handleNewConversation = useCallback(() => {
    if (typeof window !== "undefined") {
      sessionStorage.removeItem(STORAGE_KEY);
      sessionStorage.removeItem(SESSION_KEY);
    }
    sessionId.current = getSessionId();
    setMessages([buildWelcomeMessage(lang)]);
    setPendingCapture(null);
    setCaptureConfirmed(false);
    setSatisfactionGiven(false);
    setInput("");
  }, [lang]);

  // ── Main send handler — always free-form, always goes to the AI ────────────

  const handleSend = useCallback(
    async (text?: string) => {
      const val = (text ?? input).trim();
      if (!val || loading) return;
      setInput("");

      const detectedLang = detectLangFromText(val);
      const activeLang = detectedLang !== "en" ? detectedLang : lang;
      if (activeLang !== lang) updateLang(activeLang);

      addMessage({ role: "user", text: val });

      // Silent, non-blocking contact capture: if we're waiting on a name/email
      // for a support escalation or lead, and this message contains an email,
      // file it in the background. The input box never locks into a special
      // mode for this — it's just a normal chat message either way.
      if (pendingCapture) {
        const email = extractEmail(val);
        if (email) {
          const name = extractName(val, email);
          const capture = pendingCapture;
          setPendingCapture(null);
          const ok = capture.kind === "escalation"
            ? await submitSupportTicket({ name, email, issue: capture.issueText, sessionId: sessionId.current })
            : await submitLead({ name, email, sessionId: sessionId.current, pageUrl: typeof window !== "undefined" ? window.location.href : "" });
          if (ok) setCaptureConfirmed(true);
        }
      }

      setLoading(true);
      try {
        const history = [...messages, { id: "tmp", role: "user" as const, text: val }];
        const apiMessages = history
          .filter((m) => m.role === "user" || m.role === "assistant")
          .map((m) => ({ role: m.role, content: m.text }));

        const res = await fetch("/api/public/chat", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            messages: apiMessages,
            sessionId: sessionId.current,
            pageUrl: typeof window !== "undefined" ? window.location.href : "",
          }),
        });

        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data: ApiResponse = await res.json();

        const replyLang = data.detectedLanguage || activeLang;
        if (replyLang !== lang) updateLang(replyLang);

        if (data.escalate && !pendingCapture) {
          setPendingCapture({ kind: "escalation", issueText: val });
        } else if (data.captureLeadBefore && !pendingCapture) {
          setPendingCapture({ kind: "lead", issueText: val, pendingHref: data.ctaLink?.href || "https://www.jobbidder.io/login" });
        }

        addMessage({ role: "assistant", text: stripMarkdown(data.reply), ctaLink: data.ctaLink });
      } catch {
        addMessage({ role: "assistant", text: t(lang, "error_fallback"), isError: true });
      } finally {
        setLoading(false);
      }
    },
    [input, loading, lang, messages, pendingCapture, addMessage, updateLang]
  );

  const handleKey = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  // ── Satisfaction handler ─────────────────────────────────────────────────────

  const handleSatisfaction = useCallback(
    (positive: boolean) => {
      setSatisfactionGiven(true);
      setTimeout(() => addMessage({ role: "assistant", text: positive ? t(lang, "satisfaction_thanks") : t(lang, "satisfaction_sorry") }), 200);
    },
    [lang, addMessage]
  );

  // ─── Render ───────────────────────────────────────────────────────────────────

  return (
    <>
      {/* ── Launcher button — hidden on mobile (Jessica takes over) ── */}
      <button
        onClick={() => setOpen((o) => !o)}
        className="fixed bottom-6 right-6 z-[9997] hidden sm:flex h-14 w-14 items-center justify-center rounded-full bg-primary text-white shadow-xl transition-all duration-200 hover:scale-105 hover:shadow-2xl focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/60 active:scale-95"
        aria-label={open ? "Close chat" : "Open Jobbidder AI chat"}
      >
        <span
          className="absolute inset-0 flex items-center justify-center transition-all duration-200"
          style={{ opacity: open ? 0 : 1, transform: open ? "scale(0.7) rotate(90deg)" : "scale(1) rotate(0deg)" }}
        >
          <MessageCircle className="h-6 w-6" />
        </span>
        <span
          className="absolute inset-0 flex items-center justify-center transition-all duration-200"
          style={{ opacity: open ? 1 : 0, transform: open ? "scale(1) rotate(0deg)" : "scale(0.7) rotate(-90deg)" }}
        >
          <ChevronDown className="h-6 w-6" />
        </span>
        {!open && unread > 0 && (
          <span className="absolute -top-1 -right-1 flex h-5 w-5 items-center justify-center rounded-full bg-red-500 text-[10px] font-bold text-white shadow">
            {unread > 9 ? "9+" : unread}
          </span>
        )}
      </button>

      {/* ── Chat panel — hidden on mobile (Jessica takes over) ── */}
      <div
        className="fixed bottom-24 right-6 z-[9997] hidden sm:flex flex-col rounded-2xl border border-border bg-card shadow-2xl transition-all duration-300 origin-bottom-right"
        style={{
          width: "min(380px, calc(100vw - 1.5rem))",
          maxHeight: "min(560px, calc(100vh - 8rem))",
          opacity: open ? 1 : 0,
          transform: open ? "scale(1) translateY(0)" : "scale(0.95) translateY(8px)",
          pointerEvents: open ? "auto" : "none",
        }}
        role="dialog"
        aria-label="Jobbidder AI Assistant"
        aria-hidden={!open}
      >
        {/* Header */}
        <div className="flex items-center gap-3 rounded-t-2xl bg-primary px-4 py-3 shrink-0">
          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-white/20">
            <MessageCircle className="h-5 w-5 text-white" />
          </div>
          <div className="min-w-0 flex-1">
            <p className="text-sm font-bold text-white leading-tight">Jobbidder AI</p>
            <p className="text-xs text-white/70 leading-tight">{t(lang, "header_subtitle")}</p>
          </div>
          <div className="flex items-center gap-1.5 mr-1">
            <span className={`h-2 w-2 rounded-full ${online ? "bg-green-400 shadow-[0_0_4px_rgba(74,222,128,0.8)]" : "bg-yellow-400"}`} />
            <span className="text-[10px] text-white/60">{t(lang, online ? "online" : "offline")}</span>
          </div>
          <button
            onClick={handleNewConversation}
            className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-white/70 hover:bg-white/20 hover:text-white transition"
            aria-label={t(lang, "new_conversation")}
            title={t(lang, "new_conversation")}
          >
            <RotateCcw className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={() => setOpen(false)}
            className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-white/70 hover:bg-white/20 hover:text-white transition"
            aria-label="Close chat"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Messages */}
        <div className="flex flex-col gap-3 overflow-y-auto p-4 flex-1" style={{ minHeight: "200px" }}>
          {messages.map((m) => (
            <div key={m.id} className={`flex flex-col gap-2 ${m.role === "user" ? "items-end" : "items-start"}`}>
              <div
                className={`max-w-[85%] rounded-2xl px-3.5 py-2.5 text-sm leading-relaxed ${
                  m.role === "user"
                    ? "bg-primary text-white rounded-br-sm"
                    : m.isError
                    ? "bg-red-50 text-red-700 border border-red-200 rounded-bl-sm"
                    : "bg-muted text-foreground rounded-bl-sm"
                }`}
              >
                {m.isError && <AlertCircle className="inline h-3.5 w-3.5 mr-1 -mt-0.5" />}
                {parseTextWithLinks(m.text)}
              </div>

              {m.ctaLink && (
                <a
                  href={m.ctaLink.href}
                  target={m.ctaLink.href.startsWith("http") ? "_blank" : "_self"}
                  rel="noreferrer"
                  className="inline-flex items-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-primary/90 transition"
                >
                  {m.ctaLink.label}
                  {m.ctaLink.href.startsWith("http") && <ExternalLink className="h-3.5 w-3.5 opacity-70" />}
                </a>
              )}

              {m.showSatisfaction && !satisfactionGiven && (
                <div className="flex items-center gap-2 mt-1">
                  <span className="text-xs text-muted-foreground">{t(lang, "satisfaction_prompt")}</span>
                  <button
                    onClick={() => handleSatisfaction(true)}
                    className="flex items-center gap-1 rounded-full border border-green-200 bg-green-50 px-2.5 py-1 text-xs font-semibold text-green-700 hover:bg-green-100 transition"
                  >
                    <ThumbsUp className="h-3 w-3" />
                    {t(lang, "satisfaction_yes")}
                  </button>
                  <button
                    onClick={() => handleSatisfaction(false)}
                    className="flex items-center gap-1 rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-xs font-semibold text-red-700 hover:bg-red-100 transition"
                  >
                    <ThumbsDown className="h-3 w-3" />
                    {t(lang, "satisfaction_no")}
                  </button>
                </div>
              )}
            </div>
          ))}

          {loading && (
            <div className="flex items-start">
              <div className="flex items-center gap-1.5 rounded-2xl rounded-bl-sm bg-muted px-3.5 py-3">
                <span className="h-2 w-2 rounded-full bg-muted-foreground/50 animate-bounce [animation-delay:0ms]" />
                <span className="h-2 w-2 rounded-full bg-muted-foreground/50 animate-bounce [animation-delay:160ms]" />
                <span className="h-2 w-2 rounded-full bg-muted-foreground/50 animate-bounce [animation-delay:320ms]" />
              </div>
            </div>
          )}

          {captureConfirmed && (
            <div className="flex items-center justify-center gap-2 rounded-xl bg-green-50 border border-green-200 px-3 py-2 text-xs font-semibold text-green-700">
              <CheckCircle2 className="h-4 w-4 shrink-0" />
              {t(lang, "ticket_submitted")}
            </div>
          )}

          <div ref={bottomRef} />
        </div>

        {/* Input */}
        <div className="flex items-center gap-2 border-t border-border px-3 py-3 shrink-0">
          <input
            ref={inputRef}
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKey}
            placeholder={t(lang, "placeholder_default")}
            disabled={loading}
            className="flex-1 min-w-0 rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none transition focus:ring-2 focus:ring-primary/30 disabled:opacity-50 disabled:cursor-not-allowed"
          />
          <button
            onClick={() => handleSend()}
            disabled={!input.trim() || loading}
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary text-white transition hover:bg-primary/90 disabled:opacity-40 active:scale-95"
            aria-label="Send message"
          >
            {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
          </button>
        </div>

        {/* Footer */}
        <div className="rounded-b-2xl border-t border-border/50 px-4 py-2 text-center shrink-0">
          <p className="text-[10px] text-muted-foreground/60">
            {t(lang, "powered_by")}{" "}
            <a href="/terms" className="underline hover:text-muted-foreground transition">
              {t(lang, "terms")}
            </a>
          </p>
        </div>
      </div>
    </>
  );
}
