/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyJobbidderRouteImport } from './routes/why-jobbidder'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SmsTermsRouteImport } from './routes/sms-terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalIdRouteImport } from './routes/proposal.$id'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as EIdRouteImport } from './routes/e.$id'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedGhlSetupRouteImport } from './routes/_authenticated.ghl-setup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTestSmsGhlRouteImport } from './routes/api/public/test-sms-ghl'
import { Route as ApiPublicTestProposalFlowRouteImport } from './routes/api/public/test-proposal-flow'
import { Route as ApiPublicSendProposalEmailRouteImport } from './routes/api/public/send-proposal-email'
import { Route as ApiPublicProposalViewRouteImport } from './routes/api/public/proposal-view'
import { Route as ApiPublicProposalRouteImport } from './routes/api/public/proposal'
import { Route as ApiPublicIntakeSubmitRouteImport } from './routes/api/public/intake-submit'
import { Route as ApiPublicDefaultContractorRouteImport } from './routes/api/public/default-contractor'
import { Route as ApiPublicDeclineProposalRouteImport } from './routes/api/public/decline-proposal'
import { Route as ApiPublicCreateDepositInvoiceRouteImport } from './routes/api/public/create-deposit-invoice'
import { Route as ApiPublicAcceptProposalRouteImport } from './routes/api/public/accept-proposal'
import { Route as AuthenticatedProposalsNewRouteImport } from './routes/_authenticated.proposals.new'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWebhookGhlPaymentRouteImport } from './routes/api/public/webhook.ghl-payment'
import { Route as ApiPublicWebhookGhlRouteImport } from './routes/api/public/webhook.ghl'
import { Route as ApiPublicWebhookGhlJessicaFollowupRouteImport } from './routes/api/public/webhook.ghl-jessica-followup'
import { Route as ApiPublicHooksProcessFollowupsRouteImport } from './routes/api/public/hooks/process-followups'
import { Route as ApiPublicHooksProcessJessicaFollowupsRouteImport } from './routes/api/public/hooks/process-jessica-followups'
import { Route as ContractorApplyRouteImport } from './routes/contractor-apply'
import { Route as ApiPublicContractorApplyRouteImport } from './routes/api/public/contractor-apply'
import { Route as ApiPublicContractorRecruitRouteImport } from './routes/api/public/contractor-recruit'

const WhyJobbidderRoute = WhyJobbidderRouteImport.update({
  id: '/why-jobbidder',
  path: '/why-jobbidder',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsTermsRoute = SmsTermsRouteImport.update({
  id: '/sms-terms',
  path: '/sms-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalIdRoute = ProposalIdRouteImport.update({
  id: '/proposal/$id',
  path: '/proposal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EIdRoute = EIdRouteImport.update({
  id: '/e/$id',
  path: '/e/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGhlSetupRoute = AuthenticatedGhlSetupRouteImport.update({
  id: '/ghl-setup',
  path: '/ghl-setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestSmsGhlRoute = ApiPublicTestSmsGhlRouteImport.update({
  id: '/api/public/test-sms-ghl',
  path: '/api/public/test-sms-ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestProposalFlowRoute =
  ApiPublicTestProposalFlowRouteImport.update({
    id: '/api/public/test-proposal-flow',
    path: '/api/public/test-proposal-flow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendProposalEmailRoute =
  ApiPublicSendProposalEmailRouteImport.update({
    id: '/api/public/send-proposal-email',
    path: '/api/public/send-proposal-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProposalViewRoute = ApiPublicProposalViewRouteImport.update({
  id: '/api/public/proposal-view',
  path: '/api/public/proposal-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProposalRoute = ApiPublicProposalRouteImport.update({
  id: '/api/public/proposal',
  path: '/api/public/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntakeSubmitRoute = ApiPublicIntakeSubmitRouteImport.update({
  id: '/api/public/intake-submit',
  path: '/api/public/intake-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDefaultContractorRoute =
  ApiPublicDefaultContractorRouteImport.update({
    id: '/api/public/default-contractor',
    path: '/api/public/default-contractor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeclineProposalRoute =
  ApiPublicDeclineProposalRouteImport.update({
    id: '/api/public/decline-proposal',
    path: '/api/public/decline-proposal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateDepositInvoiceRoute =
  ApiPublicCreateDepositInvoiceRouteImport.update({
    id: '/api/public/create-deposit-invoice',
    path: '/api/public/create-deposit-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAcceptProposalRoute = ApiPublicAcceptProposalRouteImport.update({
  id: '/api/public/accept-proposal',
  path: '/api/public/accept-proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProposalsNewRoute =
  AuthenticatedProposalsNewRouteImport.update({
    id: '/proposals/new',
    path: '/proposals/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookGhlPaymentRoute =
  ApiPublicWebhookGhlPaymentRouteImport.update({
    id: '/api/public/webhook/ghl-payment',
    path: '/api/public/webhook/ghl-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookGhlRoute = ApiPublicWebhookGhlRouteImport.update({
  id: '/api/public/webhook/ghl',
  path: '/api/public/webhook/ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookGhlJessicaFollowupRoute =
  ApiPublicWebhookGhlJessicaFollowupRouteImport.update({
    id: '/api/public/webhook/ghl-jessica-followup',
    path: '/api/public/webhook/ghl-jessica-followup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessFollowupsRoute =
  ApiPublicHooksProcessFollowupsRouteImport.update({
    id: '/api/public/hooks/process-followups',
    path: '/api/public/hooks/process-followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessJessicaFollowupsRoute =
  ApiPublicHooksProcessJessicaFollowupsRouteImport.update({
    id: '/api/public/hooks/process-jessica-followups',
    path: '/api/public/hooks/process-jessica-followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContractorApplyRoute = ContractorApplyRouteImport.update({
  id: '/contractor-apply',
  path: '/contractor-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContractorApplyRoute = ApiPublicContractorApplyRouteImport.update({
  id: '/api/public/contractor-apply',
  path: '/api/public/contractor-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContractorRecruitRoute = ApiPublicContractorRecruitRouteImport.update({
  id: '/api/public/contractor-recruit',
  path: '/api/public/contractor-recruit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-jobbidder': typeof WhyJobbidderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ghl-setup': typeof AuthenticatedGhlSetupRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/e/$id': typeof EIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$id': typeof PIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/api/public/accept-proposal': typeof ApiPublicAcceptProposalRoute
  '/api/public/create-deposit-invoice': typeof ApiPublicCreateDepositInvoiceRoute
  '/api/public/decline-proposal': typeof ApiPublicDeclineProposalRoute
  '/api/public/default-contractor': typeof ApiPublicDefaultContractorRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
  '/api/public/proposal': typeof ApiPublicProposalRoute
  '/api/public/proposal-view': typeof ApiPublicProposalViewRoute
  '/api/public/send-proposal-email': typeof ApiPublicSendProposalEmailRoute
  '/api/public/test-proposal-flow': typeof ApiPublicTestProposalFlowRoute
  '/api/public/test-sms-ghl': typeof ApiPublicTestSmsGhlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-jessica-followups': typeof ApiPublicHooksProcessJessicaFollowupsRoute
  '/api/public/webhook/ghl': typeof ApiPublicWebhookGhlRoute
  '/api/public/webhook/ghl-jessica-followup': typeof ApiPublicWebhookGhlJessicaFollowupRoute
  '/api/public/webhook/ghl-payment': typeof ApiPublicWebhookGhlPaymentRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/contractor-apply': typeof ContractorApplyRoute
  '/api/public/contractor-apply': typeof ApiPublicContractorApplyRoute
  '/api/public/contractor-recruit': typeof ApiPublicContractorRecruitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-jobbidder': typeof WhyJobbidderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ghl-setup': typeof AuthenticatedGhlSetupRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/e/$id': typeof EIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$id': typeof PIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/api/public/accept-proposal': typeof ApiPublicAcceptProposalRoute
  '/api/public/create-deposit-invoice': typeof ApiPublicCreateDepositInvoiceRoute
  '/api/public/decline-proposal': typeof ApiPublicDeclineProposalRoute
  '/api/public/default-contractor': typeof ApiPublicDefaultContractorRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
  '/api/public/proposal': typeof ApiPublicProposalRoute
  '/api/public/proposal-view': typeof ApiPublicProposalViewRoute
  '/api/public/send-proposal-email': typeof ApiPublicSendProposalEmailRoute
  '/api/public/test-proposal-flow': typeof ApiPublicTestProposalFlowRoute
  '/api/public/test-sms-ghl': typeof ApiPublicTestSmsGhlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-jessica-followups': typeof ApiPublicHooksProcessJessicaFollowupsRoute
  '/api/public/webhook/ghl': typeof ApiPublicWebhookGhlRoute
  '/api/public/webhook/ghl-jessica-followup': typeof ApiPublicWebhookGhlJessicaFollowupRoute
  '/api/public/webhook/ghl-payment': typeof ApiPublicWebhookGhlPaymentRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/contractor-apply': typeof ContractorApplyRoute
  '/api/public/contractor-apply': typeof ApiPublicContractorApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-jobbidder': typeof WhyJobbidderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ghl-setup': typeof AuthenticatedGhlSetupRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/e/$id': typeof EIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$id': typeof PIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/_authenticated/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/api/public/accept-proposal': typeof ApiPublicAcceptProposalRoute
  '/api/public/create-deposit-invoice': typeof ApiPublicCreateDepositInvoiceRoute
  '/api/public/decline-proposal': typeof ApiPublicDeclineProposalRoute
  '/api/public/default-contractor': typeof ApiPublicDefaultContractorRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
  '/api/public/proposal': typeof ApiPublicProposalRoute
  '/api/public/proposal-view': typeof ApiPublicProposalViewRoute
  '/api/public/send-proposal-email': typeof ApiPublicSendProposalEmailRoute
  '/api/public/test-proposal-flow': typeof ApiPublicTestProposalFlowRoute
  '/api/public/test-sms-ghl': typeof ApiPublicTestSmsGhlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-jessica-followups': typeof ApiPublicHooksProcessJessicaFollowupsRoute
  '/api/public/webhook/ghl': typeof ApiPublicWebhookGhlRoute
  '/api/public/webhook/ghl-jessica-followup': typeof ApiPublicWebhookGhlJessicaFollowupRoute
  '/api/public/webhook/ghl-payment': typeof ApiPublicWebhookGhlPaymentRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/contractor-apply': typeof ContractorApplyRoute
  '/api/public/contractor-apply': typeof ApiPublicContractorApplyRoute
  '/api/public/contractor-recruit': typeof ApiPublicContractorRecruitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sms-terms'
    | '/terms'
    | '/unsubscribe'
    | '/why-jobbidder'
    | '/dashboard'
    | '/ghl-setup'
    | '/settings'
    | '/e/$id'
    | '/email/unsubscribe'
    | '/p/$id'
    | '/proposal/$id'
    | '/proposals/new'
    | '/api/public/accept-proposal'
    | '/api/public/create-deposit-invoice'
    | '/api/public/decline-proposal'
    | '/api/public/default-contractor'
    | '/api/public/intake-submit'
    | '/api/public/proposal'
    | '/api/public/proposal-view'
    | '/api/public/send-proposal-email'
    | '/api/public/test-proposal-flow'
    | '/api/public/test-sms-ghl'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-jessica-followups'
    | '/api/public/webhook/ghl'
    | '/api/public/webhook/ghl-jessica-followup'
    | '/api/public/webhook/ghl-payment'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/contractor-apply'
    | '/api/public/contractor-apply'
    | '/api/public/contractor-recruit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sms-terms'
    | '/terms'
    | '/unsubscribe'
    | '/why-jobbidder'
    | '/dashboard'
    | '/ghl-setup'
    | '/settings'
    | '/e/$id'
    | '/email/unsubscribe'
    | '/p/$id'
    | '/proposal/$id'
    | '/proposals/new'
    | '/api/public/accept-proposal'
    | '/api/public/create-deposit-invoice'
    | '/api/public/decline-proposal'
    | '/api/public/default-contractor'
    | '/api/public/intake-submit'
    | '/api/public/proposal'
    | '/api/public/proposal-view'
    | '/api/public/send-proposal-email'
    | '/api/public/test-proposal-flow'
    | '/api/public/test-sms-ghl'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-jessica-followups'
    | '/api/public/webhook/ghl'
    | '/api/public/webhook/ghl-jessica-followup'
    | '/api/public/webhook/ghl-payment'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/contractor-apply'
    | '/api/public/contractor-apply'
    | '/api/public/contractor-recruit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sms-terms'
    | '/terms'
    | '/unsubscribe'
    | '/why-jobbidder'
    | '/_authenticated/dashboard'
    | '/_authenticated/ghl-setup'
    | '/_authenticated/settings'
    | '/e/$id'
    | '/email/unsubscribe'
    | '/p/$id'
    | '/proposal/$id'
    | '/_authenticated/proposals/new'
    | '/api/public/accept-proposal'
    | '/api/public/create-deposit-invoice'
    | '/api/public/decline-proposal'
    | '/api/public/default-contractor'
    | '/api/public/intake-submit'
    | '/api/public/proposal'
    | '/api/public/proposal-view'
    | '/api/public/send-proposal-email'
    | '/api/public/test-proposal-flow'
    | '/api/public/test-sms-ghl'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-jessica-followups'
    | '/api/public/webhook/ghl'
    | '/api/public/webhook/ghl-jessica-followup'
    | '/api/public/webhook/ghl-payment'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/contractor-apply'
    | '/api/public/contractor-apply'
    | '/api/public/contractor-recruit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SmsTermsRoute: typeof SmsTermsRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WhyJobbidderRoute: typeof WhyJobbidderRoute
  EIdRoute: typeof EIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PIdRoute: typeof PIdRoute
  ProposalIdRoute: typeof ProposalIdRoute
  ApiPublicAcceptProposalRoute: typeof ApiPublicAcceptProposalRoute
  ApiPublicCreateDepositInvoiceRoute: typeof ApiPublicCreateDepositInvoiceRoute
  ApiPublicDeclineProposalRoute: typeof ApiPublicDeclineProposalRoute
  ApiPublicDefaultContractorRoute: typeof ApiPublicDefaultContractorRoute
  ApiPublicIntakeSubmitRoute: typeof ApiPublicIntakeSubmitRoute
  ApiPublicProposalRoute: typeof ApiPublicProposalRoute
  ApiPublicProposalViewRoute: typeof ApiPublicProposalViewRoute
  ApiPublicSendProposalEmailRoute: typeof ApiPublicSendProposalEmailRoute
  ApiPublicTestProposalFlowRoute: typeof ApiPublicTestProposalFlowRoute
  ApiPublicTestSmsGhlRoute: typeof ApiPublicTestSmsGhlRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksProcessFollowupsRoute: typeof ApiPublicHooksProcessFollowupsRoute
  ApiPublicHooksProcessJessicaFollowupsRoute: typeof ApiPublicHooksProcessJessicaFollowupsRoute
  ApiPublicWebhookGhlRoute: typeof ApiPublicWebhookGhlRoute
  ApiPublicWebhookGhlJessicaFollowupRoute: typeof ApiPublicWebhookGhlJessicaFollowupRoute
  ApiPublicWebhookGhlPaymentRoute: typeof ApiPublicWebhookGhlPaymentRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ContractorApplyRoute: typeof ContractorApplyRoute
  ApiPublicContractorApplyRoute: typeof ApiPublicContractorApplyRoute
  ApiPublicContractorRecruitRoute: typeof ApiPublicContractorRecruitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-jobbidder': {
      id: '/why-jobbidder'
      path: '/why-jobbidder'
      fullPath: '/why-jobbidder'
      preLoaderRoute: typeof WhyJobbidderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-terms': {
      id: '/sms-terms'
      path: '/sms-terms'
      fullPath: '/sms-terms'
      preLoaderRoute: typeof SmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$id': {
      id: '/proposal/$id'
      path: '/proposal/$id'
      fullPath: '/proposal/$id'
      preLoaderRoute: typeof ProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$id': {
      id: '/e/$id'
      path: '/e/$id'
      fullPath: '/e/$id'
      preLoaderRoute: typeof EIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ghl-setup': {
      id: '/_authenticated/ghl-setup'
      path: '/ghl-setup'
      fullPath: '/ghl-setup'
      preLoaderRoute: typeof AuthenticatedGhlSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-sms-ghl': {
      id: '/api/public/test-sms-ghl'
      path: '/api/public/test-sms-ghl'
      fullPath: '/api/public/test-sms-ghl'
      preLoaderRoute: typeof ApiPublicTestSmsGhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-proposal-flow': {
      id: '/api/public/test-proposal-flow'
      path: '/api/public/test-proposal-flow'
      fullPath: '/api/public/test-proposal-flow'
      preLoaderRoute: typeof ApiPublicTestProposalFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-proposal-email': {
      id: '/api/public/send-proposal-email'
      path: '/api/public/send-proposal-email'
      fullPath: '/api/public/send-proposal-email'
      preLoaderRoute: typeof ApiPublicSendProposalEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposal-view': {
      id: '/api/public/proposal-view'
      path: '/api/public/proposal-view'
      fullPath: '/api/public/proposal-view'
      preLoaderRoute: typeof ApiPublicProposalViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposal': {
      id: '/api/public/proposal'
      path: '/api/public/proposal'
      fullPath: '/api/public/proposal'
      preLoaderRoute: typeof ApiPublicProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intake-submit': {
      id: '/api/public/intake-submit'
      path: '/api/public/intake-submit'
      fullPath: '/api/public/intake-submit'
      preLoaderRoute: typeof ApiPublicIntakeSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/default-contractor': {
      id: '/api/public/default-contractor'
      path: '/api/public/default-contractor'
      fullPath: '/api/public/default-contractor'
      preLoaderRoute: typeof ApiPublicDefaultContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/decline-proposal': {
      id: '/api/public/decline-proposal'
      path: '/api/public/decline-proposal'
      fullPath: '/api/public/decline-proposal'
      preLoaderRoute: typeof ApiPublicDeclineProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-deposit-invoice': {
      id: '/api/public/create-deposit-invoice'
      path: '/api/public/create-deposit-invoice'
      fullPath: '/api/public/create-deposit-invoice'
      preLoaderRoute: typeof ApiPublicCreateDepositInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/accept-proposal': {
      id: '/api/public/accept-proposal'
      path: '/api/public/accept-proposal'
      fullPath: '/api/public/accept-proposal'
      preLoaderRoute: typeof ApiPublicAcceptProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/proposals/new': {
      id: '/_authenticated/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthenticatedProposalsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/ghl-payment': {
      id: '/api/public/webhook/ghl-payment'
      path: '/api/public/webhook/ghl-payment'
      fullPath: '/api/public/webhook/ghl-payment'
      preLoaderRoute: typeof ApiPublicWebhookGhlPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/ghl': {
      id: '/api/public/webhook/ghl'
      path: '/api/public/webhook/ghl'
      fullPath: '/api/public/webhook/ghl'
      preLoaderRoute: typeof ApiPublicWebhookGhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/ghl-jessica-followup': {
      id: '/api/public/webhook/ghl-jessica-followup'
      path: '/api/public/webhook/ghl-jessica-followup'
      fullPath: '/api/public/webhook/ghl-jessica-followup'
      preLoaderRoute: typeof ApiPublicWebhookGhlJessicaFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-followups': {
      id: '/api/public/hooks/process-followups'
      path: '/api/public/hooks/process-followups'
      fullPath: '/api/public/hooks/process-followups'
      preLoaderRoute: typeof ApiPublicHooksProcessFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-jessica-followups': {
      id: '/api/public/hooks/process-jessica-followups'
      path: '/api/public/hooks/process-jessica-followups'
      fullPath: '/api/public/hooks/process-jessica-followups'
      preLoaderRoute: typeof ApiPublicHooksProcessJessicaFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-apply': {
      id: '/contractor-apply'
      path: '/contractor-apply'
      fullPath: '/contractor-apply'
      preLoaderRoute: typeof ContractorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contractor-apply': {
      id: '/api/public/contractor-apply'
      path: '/api/public/contractor-apply'
      fullPath: '/api/public/contractor-apply'
      preLoaderRoute: typeof ApiPublicContractorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contractor-recruit': {
      id: '/api/public/contractor-recruit'
      path: '/api/public/contractor-recruit'
      fullPath: '/api/public/contractor-recruit'
      preLoaderRoute: typeof ApiPublicContractorRecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGhlSetupRoute: typeof AuthenticatedGhlSetupRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProposalsNewRoute: typeof AuthenticatedProposalsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGhlSetupRoute: AuthenticatedGhlSetupRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProposalsNewRoute: AuthenticatedProposalsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SmsTermsRoute: SmsTermsRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WhyJobbidderRoute: WhyJobbidderRoute,
  EIdRoute: EIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PIdRoute: PIdRoute,
  ProposalIdRoute: ProposalIdRoute,
  ApiPublicAcceptProposalRoute: ApiPublicAcceptProposalRoute,
  ApiPublicCreateDepositInvoiceRoute: ApiPublicCreateDepositInvoiceRoute,
  ApiPublicDeclineProposalRoute: ApiPublicDeclineProposalRoute,
  ApiPublicDefaultContractorRoute: ApiPublicDefaultContractorRoute,
  ApiPublicIntakeSubmitRoute: ApiPublicIntakeSubmitRoute,
  ApiPublicProposalRoute: ApiPublicProposalRoute,
  ApiPublicProposalViewRoute: ApiPublicProposalViewRoute,
  ApiPublicSendProposalEmailRoute: ApiPublicSendProposalEmailRoute,
  ApiPublicTestProposalFlowRoute: ApiPublicTestProposalFlowRoute,
  ApiPublicTestSmsGhlRoute: ApiPublicTestSmsGhlRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksProcessFollowupsRoute: ApiPublicHooksProcessFollowupsRoute,
  ApiPublicHooksProcessJessicaFollowupsRoute: ApiPublicHooksProcessJessicaFollowupsRoute,
  ApiPublicWebhookGhlRoute: ApiPublicWebhookGhlRoute,
  ApiPublicWebhookGhlJessicaFollowupRoute: ApiPublicWebhookGhlJessicaFollowupRoute,
  ApiPublicWebhookGhlPaymentRoute: ApiPublicWebhookGhlPaymentRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ContractorApplyRoute: ContractorApplyRoute,
  ApiPublicContractorApplyRoute: ApiPublicContractorApplyRoute,
  ApiPublicContractorRecruitRoute: ApiPublicContractorRecruitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
