/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyJobbidderRouteImport } from './routes/why-jobbidder'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SmsTermsRouteImport } from './routes/sms-terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContractorApplyRouteImport } from './routes/contractor-apply'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalIdRouteImport } from './routes/proposal.$id'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as GoSlugRouteImport } from './routes/go.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as EIdRouteImport } from './routes/e.$id'
import { Route as AuditTokenRouteImport } from './routes/audit.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated.pipeline'
import { Route as AuthenticatedMediaUploadRouteImport } from './routes/_authenticated.media-upload'
import { Route as AuthenticatedGhlSetupRouteImport } from './routes/_authenticated.ghl-setup'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContractorVerificationRouteImport } from './routes/_authenticated.contractor-verification'
import { Route as AuthenticatedContractorSearchRouteImport } from './routes/_authenticated.contractor-search'
import { Route as AuthenticatedContractorDashboardRouteImport } from './routes/_authenticated.contractor-dashboard'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated.affiliate'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTestSmsGhlRouteImport } from './routes/api/public/test-sms-ghl'
import { Route as ApiPublicTestProposalFlowRouteImport } from './routes/api/public/test-proposal-flow'
import { Route as ApiPublicTestEmailGhlRouteImport } from './routes/api/public/test-email-ghl'
import { Route as ApiPublicSendProposalEmailRouteImport } from './routes/api/public/send-proposal-email'
import { Route as ApiPublicProposalViewRouteImport } from './routes/api/public/proposal-view'
import { Route as ApiPublicProposalRouteImport } from './routes/api/public/proposal'
import { Route as ApiPublicIntakeSubmitRouteImport } from './routes/api/public/intake-submit'
import { Route as ApiPublicDefaultContractorRouteImport } from './routes/api/public/default-contractor'
import { Route as ApiPublicDeclineProposalRouteImport } from './routes/api/public/decline-proposal'
import { Route as ApiPublicCreateDepositInvoiceRouteImport } from './routes/api/public/create-deposit-invoice'
import { Route as ApiPublicContractorRecruitRouteImport } from './routes/api/public/contractor-recruit'
import { Route as ApiPublicContractorApplyRouteImport } from './routes/api/public/contractor-apply'
import { Route as ApiPublicAcceptProposalRouteImport } from './routes/api/public/accept-proposal'
import { Route as AuthenticatedProposalsNewRouteImport } from './routes/_authenticated.proposals.new'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWebhookGhlVoicePrequalRouteImport } from './routes/api/public/webhook.ghl-voice-prequal'
import { Route as ApiPublicWebhookGhlPaymentRouteImport } from './routes/api/public/webhook.ghl-payment'
import { Route as ApiPublicWebhookGhlJessicaFollowupRouteImport } from './routes/api/public/webhook.ghl-jessica-followup'
import { Route as ApiPublicWebhookGhlContractorSurveyRouteImport } from './routes/api/public/webhook.ghl-contractor-survey'
import { Route as ApiPublicWebhookGhlRouteImport } from './routes/api/public/webhook.ghl'
import { Route as ApiPublicHooksProcessJessicaFollowupsRouteImport } from './routes/api/public/hooks/process-jessica-followups'
import { Route as ApiPublicHooksProcessFollowupsRouteImport } from './routes/api/public/hooks/process-followups'

const WhyJobbidderRoute = WhyJobbidderRouteImport.update({
  id: '/why-jobbidder',
  path: '/why-jobbidder',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsTermsRoute = SmsTermsRouteImport.update({
  id: '/sms-terms',
  path: '/sms-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorApplyRoute = ContractorApplyRouteImport.update({
  id: '/contractor-apply',
  path: '/contractor-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalIdRoute = ProposalIdRouteImport.update({
  id: '/proposal/$id',
  path: '/proposal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EIdRoute = EIdRouteImport.update({
  id: '/e/$id',
  path: '/e/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTokenRoute = AuditTokenRouteImport.update({
  id: '/audit/$token',
  path: '/audit/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMediaUploadRoute =
  AuthenticatedMediaUploadRouteImport.update({
    id: '/media-upload',
    path: '/media-upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGhlSetupRoute = AuthenticatedGhlSetupRouteImport.update({
  id: '/ghl-setup',
  path: '/ghl-setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContractorVerificationRoute =
  AuthenticatedContractorVerificationRouteImport.update({
    id: '/contractor-verification',
    path: '/contractor-verification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractorSearchRoute =
  AuthenticatedContractorSearchRouteImport.update({
    id: '/contractor-search',
    path: '/contractor-search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractorDashboardRoute =
  AuthenticatedContractorDashboardRouteImport.update({
    id: '/contractor-dashboard',
    path: '/contractor-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestSmsGhlRoute = ApiPublicTestSmsGhlRouteImport.update({
  id: '/api/public/test-sms-ghl',
  path: '/api/public/test-sms-ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestProposalFlowRoute =
  ApiPublicTestProposalFlowRouteImport.update({
    id: '/api/public/test-proposal-flow',
    path: '/api/public/test-proposal-flow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTestEmailGhlRoute = ApiPublicTestEmailGhlRouteImport.update({
  id: '/api/public/test-email-ghl',
  path: '/api/public/test-email-ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendProposalEmailRoute =
  ApiPublicSendProposalEmailRouteImport.update({
    id: '/api/public/send-proposal-email',
    path: '/api/public/send-proposal-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProposalViewRoute = ApiPublicProposalViewRouteImport.update({
  id: '/api/public/proposal-view',
  path: '/api/public/proposal-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProposalRoute = ApiPublicProposalRouteImport.update({
  id: '/api/public/proposal',
  path: '/api/public/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntakeSubmitRoute = ApiPublicIntakeSubmitRouteImport.update({
  id: '/api/public/intake-submit',
  path: '/api/public/intake-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDefaultContractorRoute =
  ApiPublicDefaultContractorRouteImport.update({
    id: '/api/public/default-contractor',
    path: '/api/public/default-contractor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeclineProposalRoute =
  ApiPublicDeclineProposalRouteImport.update({
    id: '/api/public/decline-proposal',
    path: '/api/public/decline-proposal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateDepositInvoiceRoute =
  ApiPublicCreateDepositInvoiceRouteImport.update({
    id: '/api/public/create-deposit-invoice',
    path: '/api/public/create-deposit-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContractorRecruitRoute =
  ApiPublicContractorRecruitRouteImport.update({
    id: '/api/public/contractor-recruit',
    path: '/api/public/contractor-recruit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContractorApplyRoute =
  ApiPublicContractorApplyRouteImport.update({
    id: '/api/public/contractor-apply',
    path: '/api/public/contractor-apply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAcceptProposalRoute = ApiPublicAcceptProposalRouteImport.update({
  id: '/api/public/accept-proposal',
  path: '/api/public/accept-proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProposalsNewRoute =
  AuthenticatedProposalsNewRouteImport.update({
    id: '/proposals/new',
    path: '/proposals/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookGhlVoicePrequalRoute =
  ApiPublicWebhookGhlVoicePrequalRouteImport.update({
    id: '/api/public/webhook/ghl-voice-prequal',
    path: '/api/public/webhook/ghl-voice-prequal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookGhlPaymentRoute =
  ApiPublicWebhookGhlPaymentRouteImport.update({
    id: '/api/public/webhook/ghl-payment',
    path: '/api/public/webhook/ghl-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookGhlJessicaFollowupRoute =
  ApiPublicWebhookGhlJessicaFollowupRouteImport.update({
    id: '/api/public/webhook/ghl-jessica-followup',
    path: '/api/public/webhook/ghl-jessica-followup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookGhlContractorSurveyRoute =
  ApiPublicWebhookGhlContractorSurveyRouteImport.update({
    id: '/api/public/webhook/ghl-contractor-survey',
    path: '/api/public/webhook/ghl-contractor-survey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookGhlRoute = ApiPublicWebhookGhlRouteImport.update({
  id: '/api/public/webhook/ghl',
  path: '/api/public/webhook/ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessJessicaFollowupsRoute =
  ApiPublicHooksProcessJessicaFollowupsRouteImport.update({
    id: '/api/public/hooks/process-jessica-followups',
    path: '/api/public/hooks/process-jessica-followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessFollowupsRoute =
  ApiPublicHooksProcessFollowupsRouteImport.update({
    id: '/api/public/hooks/process-followups',
    path: '/api/public/hooks/process-followups',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contractor-apply': typeof ContractorApplyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-jobbidder': typeof WhyJobbidderRoute
  '/account': typeof AuthenticatedAccountRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/contractor-dashboard': typeof AuthenticatedContractorDashboardRoute
  '/contractor-search': typeof AuthenticatedContractorSearchRoute
  '/contractor-verification': typeof AuthenticatedContractorVerificationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/ghl-setup': typeof AuthenticatedGhlSetupRoute
  '/media-upload': typeof AuthenticatedMediaUploadRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audit/$token': typeof AuditTokenRoute
  '/e/$id': typeof EIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/$slug': typeof GoSlugRoute
  '/p/$id': typeof PIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/api/public/accept-proposal': typeof ApiPublicAcceptProposalRoute
  '/api/public/contractor-apply': typeof ApiPublicContractorApplyRoute
  '/api/public/contractor-recruit': typeof ApiPublicContractorRecruitRoute
  '/api/public/create-deposit-invoice': typeof ApiPublicCreateDepositInvoiceRoute
  '/api/public/decline-proposal': typeof ApiPublicDeclineProposalRoute
  '/api/public/default-contractor': typeof ApiPublicDefaultContractorRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
  '/api/public/proposal': typeof ApiPublicProposalRoute
  '/api/public/proposal-view': typeof ApiPublicProposalViewRoute
  '/api/public/send-proposal-email': typeof ApiPublicSendProposalEmailRoute
  '/api/public/test-email-ghl': typeof ApiPublicTestEmailGhlRoute
  '/api/public/test-proposal-flow': typeof ApiPublicTestProposalFlowRoute
  '/api/public/test-sms-ghl': typeof ApiPublicTestSmsGhlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-jessica-followups': typeof ApiPublicHooksProcessJessicaFollowupsRoute
  '/api/public/webhook/ghl': typeof ApiPublicWebhookGhlRoute
  '/api/public/webhook/ghl-contractor-survey': typeof ApiPublicWebhookGhlContractorSurveyRoute
  '/api/public/webhook/ghl-jessica-followup': typeof ApiPublicWebhookGhlJessicaFollowupRoute
  '/api/public/webhook/ghl-payment': typeof ApiPublicWebhookGhlPaymentRoute
  '/api/public/webhook/ghl-voice-prequal': typeof ApiPublicWebhookGhlVoicePrequalRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contractor-apply': typeof ContractorApplyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-jobbidder': typeof WhyJobbidderRoute
  '/account': typeof AuthenticatedAccountRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/contractor-dashboard': typeof AuthenticatedContractorDashboardRoute
  '/contractor-search': typeof AuthenticatedContractorSearchRoute
  '/contractor-verification': typeof AuthenticatedContractorVerificationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/ghl-setup': typeof AuthenticatedGhlSetupRoute
  '/media-upload': typeof AuthenticatedMediaUploadRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audit/$token': typeof AuditTokenRoute
  '/e/$id': typeof EIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/$slug': typeof GoSlugRoute
  '/p/$id': typeof PIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/api/public/accept-proposal': typeof ApiPublicAcceptProposalRoute
  '/api/public/contractor-apply': typeof ApiPublicContractorApplyRoute
  '/api/public/contractor-recruit': typeof ApiPublicContractorRecruitRoute
  '/api/public/create-deposit-invoice': typeof ApiPublicCreateDepositInvoiceRoute
  '/api/public/decline-proposal': typeof ApiPublicDeclineProposalRoute
  '/api/public/default-contractor': typeof ApiPublicDefaultContractorRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
  '/api/public/proposal': typeof ApiPublicProposalRoute
  '/api/public/proposal-view': typeof ApiPublicProposalViewRoute
  '/api/public/send-proposal-email': typeof ApiPublicSendProposalEmailRoute
  '/api/public/test-email-ghl': typeof ApiPublicTestEmailGhlRoute
  '/api/public/test-proposal-flow': typeof ApiPublicTestProposalFlowRoute
  '/api/public/test-sms-ghl': typeof ApiPublicTestSmsGhlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-jessica-followups': typeof ApiPublicHooksProcessJessicaFollowupsRoute
  '/api/public/webhook/ghl': typeof ApiPublicWebhookGhlRoute
  '/api/public/webhook/ghl-contractor-survey': typeof ApiPublicWebhookGhlContractorSurveyRoute
  '/api/public/webhook/ghl-jessica-followup': typeof ApiPublicWebhookGhlJessicaFollowupRoute
  '/api/public/webhook/ghl-payment': typeof ApiPublicWebhookGhlPaymentRoute
  '/api/public/webhook/ghl-voice-prequal': typeof ApiPublicWebhookGhlVoicePrequalRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contractor-apply': typeof ContractorApplyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why-jobbidder': typeof WhyJobbidderRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRoute
  '/_authenticated/contractor-dashboard': typeof AuthenticatedContractorDashboardRoute
  '/_authenticated/contractor-search': typeof AuthenticatedContractorSearchRoute
  '/_authenticated/contractor-verification': typeof AuthenticatedContractorVerificationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/ghl-setup': typeof AuthenticatedGhlSetupRoute
  '/_authenticated/media-upload': typeof AuthenticatedMediaUploadRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/audit/$token': typeof AuditTokenRoute
  '/e/$id': typeof EIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/$slug': typeof GoSlugRoute
  '/p/$id': typeof PIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/_authenticated/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/api/public/accept-proposal': typeof ApiPublicAcceptProposalRoute
  '/api/public/contractor-apply': typeof ApiPublicContractorApplyRoute
  '/api/public/contractor-recruit': typeof ApiPublicContractorRecruitRoute
  '/api/public/create-deposit-invoice': typeof ApiPublicCreateDepositInvoiceRoute
  '/api/public/decline-proposal': typeof ApiPublicDeclineProposalRoute
  '/api/public/default-contractor': typeof ApiPublicDefaultContractorRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
  '/api/public/proposal': typeof ApiPublicProposalRoute
  '/api/public/proposal-view': typeof ApiPublicProposalViewRoute
  '/api/public/send-proposal-email': typeof ApiPublicSendProposalEmailRoute
  '/api/public/test-email-ghl': typeof ApiPublicTestEmailGhlRoute
  '/api/public/test-proposal-flow': typeof ApiPublicTestProposalFlowRoute
  '/api/public/test-sms-ghl': typeof ApiPublicTestSmsGhlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
  '/api/public/hooks/process-jessica-followups': typeof ApiPublicHooksProcessJessicaFollowupsRoute
  '/api/public/webhook/ghl': typeof ApiPublicWebhookGhlRoute
  '/api/public/webhook/ghl-contractor-survey': typeof ApiPublicWebhookGhlContractorSurveyRoute
  '/api/public/webhook/ghl-jessica-followup': typeof ApiPublicWebhookGhlJessicaFollowupRoute
  '/api/public/webhook/ghl-payment': typeof ApiPublicWebhookGhlPaymentRoute
  '/api/public/webhook/ghl-voice-prequal': typeof ApiPublicWebhookGhlVoicePrequalRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contractor-apply'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sms-terms'
    | '/terms'
    | '/unsubscribe'
    | '/why-jobbidder'
    | '/account'
    | '/affiliate'
    | '/contractor-dashboard'
    | '/contractor-search'
    | '/contractor-verification'
    | '/dashboard'
    | '/documents'
    | '/ghl-setup'
    | '/media-upload'
    | '/pipeline'
    | '/settings'
    | '/audit/$token'
    | '/e/$id'
    | '/email/unsubscribe'
    | '/go/$slug'
    | '/p/$id'
    | '/proposal/$id'
    | '/proposals/new'
    | '/api/public/accept-proposal'
    | '/api/public/contractor-apply'
    | '/api/public/contractor-recruit'
    | '/api/public/create-deposit-invoice'
    | '/api/public/decline-proposal'
    | '/api/public/default-contractor'
    | '/api/public/intake-submit'
    | '/api/public/proposal'
    | '/api/public/proposal-view'
    | '/api/public/send-proposal-email'
    | '/api/public/test-email-ghl'
    | '/api/public/test-proposal-flow'
    | '/api/public/test-sms-ghl'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-jessica-followups'
    | '/api/public/webhook/ghl'
    | '/api/public/webhook/ghl-contractor-survey'
    | '/api/public/webhook/ghl-jessica-followup'
    | '/api/public/webhook/ghl-payment'
    | '/api/public/webhook/ghl-voice-prequal'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contractor-apply'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sms-terms'
    | '/terms'
    | '/unsubscribe'
    | '/why-jobbidder'
    | '/account'
    | '/affiliate'
    | '/contractor-dashboard'
    | '/contractor-search'
    | '/contractor-verification'
    | '/dashboard'
    | '/documents'
    | '/ghl-setup'
    | '/media-upload'
    | '/pipeline'
    | '/settings'
    | '/audit/$token'
    | '/e/$id'
    | '/email/unsubscribe'
    | '/go/$slug'
    | '/p/$id'
    | '/proposal/$id'
    | '/proposals/new'
    | '/api/public/accept-proposal'
    | '/api/public/contractor-apply'
    | '/api/public/contractor-recruit'
    | '/api/public/create-deposit-invoice'
    | '/api/public/decline-proposal'
    | '/api/public/default-contractor'
    | '/api/public/intake-submit'
    | '/api/public/proposal'
    | '/api/public/proposal-view'
    | '/api/public/send-proposal-email'
    | '/api/public/test-email-ghl'
    | '/api/public/test-proposal-flow'
    | '/api/public/test-sms-ghl'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-jessica-followups'
    | '/api/public/webhook/ghl'
    | '/api/public/webhook/ghl-contractor-survey'
    | '/api/public/webhook/ghl-jessica-followup'
    | '/api/public/webhook/ghl-payment'
    | '/api/public/webhook/ghl-voice-prequal'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contractor-apply'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sms-terms'
    | '/terms'
    | '/unsubscribe'
    | '/why-jobbidder'
    | '/_authenticated/account'
    | '/_authenticated/affiliate'
    | '/_authenticated/contractor-dashboard'
    | '/_authenticated/contractor-search'
    | '/_authenticated/contractor-verification'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/ghl-setup'
    | '/_authenticated/media-upload'
    | '/_authenticated/pipeline'
    | '/_authenticated/settings'
    | '/audit/$token'
    | '/e/$id'
    | '/email/unsubscribe'
    | '/go/$slug'
    | '/p/$id'
    | '/proposal/$id'
    | '/_authenticated/proposals/new'
    | '/api/public/accept-proposal'
    | '/api/public/contractor-apply'
    | '/api/public/contractor-recruit'
    | '/api/public/create-deposit-invoice'
    | '/api/public/decline-proposal'
    | '/api/public/default-contractor'
    | '/api/public/intake-submit'
    | '/api/public/proposal'
    | '/api/public/proposal-view'
    | '/api/public/send-proposal-email'
    | '/api/public/test-email-ghl'
    | '/api/public/test-proposal-flow'
    | '/api/public/test-sms-ghl'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-followups'
    | '/api/public/hooks/process-jessica-followups'
    | '/api/public/webhook/ghl'
    | '/api/public/webhook/ghl-contractor-survey'
    | '/api/public/webhook/ghl-jessica-followup'
    | '/api/public/webhook/ghl-payment'
    | '/api/public/webhook/ghl-voice-prequal'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContractorApplyRoute: typeof ContractorApplyRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SmsTermsRoute: typeof SmsTermsRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WhyJobbidderRoute: typeof WhyJobbidderRoute
  AuditTokenRoute: typeof AuditTokenRoute
  EIdRoute: typeof EIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GoSlugRoute: typeof GoSlugRoute
  PIdRoute: typeof PIdRoute
  ProposalIdRoute: typeof ProposalIdRoute
  ApiPublicAcceptProposalRoute: typeof ApiPublicAcceptProposalRoute
  ApiPublicContractorApplyRoute: typeof ApiPublicContractorApplyRoute
  ApiPublicContractorRecruitRoute: typeof ApiPublicContractorRecruitRoute
  ApiPublicCreateDepositInvoiceRoute: typeof ApiPublicCreateDepositInvoiceRoute
  ApiPublicDeclineProposalRoute: typeof ApiPublicDeclineProposalRoute
  ApiPublicDefaultContractorRoute: typeof ApiPublicDefaultContractorRoute
  ApiPublicIntakeSubmitRoute: typeof ApiPublicIntakeSubmitRoute
  ApiPublicProposalRoute: typeof ApiPublicProposalRoute
  ApiPublicProposalViewRoute: typeof ApiPublicProposalViewRoute
  ApiPublicSendProposalEmailRoute: typeof ApiPublicSendProposalEmailRoute
  ApiPublicTestEmailGhlRoute: typeof ApiPublicTestEmailGhlRoute
  ApiPublicTestProposalFlowRoute: typeof ApiPublicTestProposalFlowRoute
  ApiPublicTestSmsGhlRoute: typeof ApiPublicTestSmsGhlRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksProcessFollowupsRoute: typeof ApiPublicHooksProcessFollowupsRoute
  ApiPublicHooksProcessJessicaFollowupsRoute: typeof ApiPublicHooksProcessJessicaFollowupsRoute
  ApiPublicWebhookGhlRoute: typeof ApiPublicWebhookGhlRoute
  ApiPublicWebhookGhlContractorSurveyRoute: typeof ApiPublicWebhookGhlContractorSurveyRoute
  ApiPublicWebhookGhlJessicaFollowupRoute: typeof ApiPublicWebhookGhlJessicaFollowupRoute
  ApiPublicWebhookGhlPaymentRoute: typeof ApiPublicWebhookGhlPaymentRoute
  ApiPublicWebhookGhlVoicePrequalRoute: typeof ApiPublicWebhookGhlVoicePrequalRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-jobbidder': {
      id: '/why-jobbidder'
      path: '/why-jobbidder'
      fullPath: '/why-jobbidder'
      preLoaderRoute: typeof WhyJobbidderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-terms': {
      id: '/sms-terms'
      path: '/sms-terms'
      fullPath: '/sms-terms'
      preLoaderRoute: typeof SmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-apply': {
      id: '/contractor-apply'
      path: '/contractor-apply'
      fullPath: '/contractor-apply'
      preLoaderRoute: typeof ContractorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$id': {
      id: '/proposal/$id'
      path: '/proposal/$id'
      fullPath: '/proposal/$id'
      preLoaderRoute: typeof ProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$id': {
      id: '/e/$id'
      path: '/e/$id'
      fullPath: '/e/$id'
      preLoaderRoute: typeof EIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/$token': {
      id: '/audit/$token'
      path: '/audit/$token'
      fullPath: '/audit/$token'
      preLoaderRoute: typeof AuditTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media-upload': {
      id: '/_authenticated/media-upload'
      path: '/media-upload'
      fullPath: '/media-upload'
      preLoaderRoute: typeof AuthenticatedMediaUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ghl-setup': {
      id: '/_authenticated/ghl-setup'
      path: '/ghl-setup'
      fullPath: '/ghl-setup'
      preLoaderRoute: typeof AuthenticatedGhlSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contractor-verification': {
      id: '/_authenticated/contractor-verification'
      path: '/contractor-verification'
      fullPath: '/contractor-verification'
      preLoaderRoute: typeof AuthenticatedContractorVerificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contractor-search': {
      id: '/_authenticated/contractor-search'
      path: '/contractor-search'
      fullPath: '/contractor-search'
      preLoaderRoute: typeof AuthenticatedContractorSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contractor-dashboard': {
      id: '/_authenticated/contractor-dashboard'
      path: '/contractor-dashboard'
      fullPath: '/contractor-dashboard'
      preLoaderRoute: typeof AuthenticatedContractorDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-sms-ghl': {
      id: '/api/public/test-sms-ghl'
      path: '/api/public/test-sms-ghl'
      fullPath: '/api/public/test-sms-ghl'
      preLoaderRoute: typeof ApiPublicTestSmsGhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-proposal-flow': {
      id: '/api/public/test-proposal-flow'
      path: '/api/public/test-proposal-flow'
      fullPath: '/api/public/test-proposal-flow'
      preLoaderRoute: typeof ApiPublicTestProposalFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-email-ghl': {
      id: '/api/public/test-email-ghl'
      path: '/api/public/test-email-ghl'
      fullPath: '/api/public/test-email-ghl'
      preLoaderRoute: typeof ApiPublicTestEmailGhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-proposal-email': {
      id: '/api/public/send-proposal-email'
      path: '/api/public/send-proposal-email'
      fullPath: '/api/public/send-proposal-email'
      preLoaderRoute: typeof ApiPublicSendProposalEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposal-view': {
      id: '/api/public/proposal-view'
      path: '/api/public/proposal-view'
      fullPath: '/api/public/proposal-view'
      preLoaderRoute: typeof ApiPublicProposalViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposal': {
      id: '/api/public/proposal'
      path: '/api/public/proposal'
      fullPath: '/api/public/proposal'
      preLoaderRoute: typeof ApiPublicProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intake-submit': {
      id: '/api/public/intake-submit'
      path: '/api/public/intake-submit'
      fullPath: '/api/public/intake-submit'
      preLoaderRoute: typeof ApiPublicIntakeSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/default-contractor': {
      id: '/api/public/default-contractor'
      path: '/api/public/default-contractor'
      fullPath: '/api/public/default-contractor'
      preLoaderRoute: typeof ApiPublicDefaultContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/decline-proposal': {
      id: '/api/public/decline-proposal'
      path: '/api/public/decline-proposal'
      fullPath: '/api/public/decline-proposal'
      preLoaderRoute: typeof ApiPublicDeclineProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-deposit-invoice': {
      id: '/api/public/create-deposit-invoice'
      path: '/api/public/create-deposit-invoice'
      fullPath: '/api/public/create-deposit-invoice'
      preLoaderRoute: typeof ApiPublicCreateDepositInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contractor-recruit': {
      id: '/api/public/contractor-recruit'
      path: '/api/public/contractor-recruit'
      fullPath: '/api/public/contractor-recruit'
      preLoaderRoute: typeof ApiPublicContractorRecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contractor-apply': {
      id: '/api/public/contractor-apply'
      path: '/api/public/contractor-apply'
      fullPath: '/api/public/contractor-apply'
      preLoaderRoute: typeof ApiPublicContractorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/accept-proposal': {
      id: '/api/public/accept-proposal'
      path: '/api/public/accept-proposal'
      fullPath: '/api/public/accept-proposal'
      preLoaderRoute: typeof ApiPublicAcceptProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/proposals/new': {
      id: '/_authenticated/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthenticatedProposalsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/ghl-voice-prequal': {
      id: '/api/public/webhook/ghl-voice-prequal'
      path: '/api/public/webhook/ghl-voice-prequal'
      fullPath: '/api/public/webhook/ghl-voice-prequal'
      preLoaderRoute: typeof ApiPublicWebhookGhlVoicePrequalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/ghl-payment': {
      id: '/api/public/webhook/ghl-payment'
      path: '/api/public/webhook/ghl-payment'
      fullPath: '/api/public/webhook/ghl-payment'
      preLoaderRoute: typeof ApiPublicWebhookGhlPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/ghl-jessica-followup': {
      id: '/api/public/webhook/ghl-jessica-followup'
      path: '/api/public/webhook/ghl-jessica-followup'
      fullPath: '/api/public/webhook/ghl-jessica-followup'
      preLoaderRoute: typeof ApiPublicWebhookGhlJessicaFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/ghl-contractor-survey': {
      id: '/api/public/webhook/ghl-contractor-survey'
      path: '/api/public/webhook/ghl-contractor-survey'
      fullPath: '/api/public/webhook/ghl-contractor-survey'
      preLoaderRoute: typeof ApiPublicWebhookGhlContractorSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/ghl': {
      id: '/api/public/webhook/ghl'
      path: '/api/public/webhook/ghl'
      fullPath: '/api/public/webhook/ghl'
      preLoaderRoute: typeof ApiPublicWebhookGhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-jessica-followups': {
      id: '/api/public/hooks/process-jessica-followups'
      path: '/api/public/hooks/process-jessica-followups'
      fullPath: '/api/public/hooks/process-jessica-followups'
      preLoaderRoute: typeof ApiPublicHooksProcessJessicaFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-followups': {
      id: '/api/public/hooks/process-followups'
      path: '/api/public/hooks/process-followups'
      fullPath: '/api/public/hooks/process-followups'
      preLoaderRoute: typeof ApiPublicHooksProcessFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRoute
  AuthenticatedContractorDashboardRoute: typeof AuthenticatedContractorDashboardRoute
  AuthenticatedContractorSearchRoute: typeof AuthenticatedContractorSearchRoute
  AuthenticatedContractorVerificationRoute: typeof AuthenticatedContractorVerificationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedGhlSetupRoute: typeof AuthenticatedGhlSetupRoute
  AuthenticatedMediaUploadRoute: typeof AuthenticatedMediaUploadRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProposalsNewRoute: typeof AuthenticatedProposalsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRoute,
  AuthenticatedContractorDashboardRoute: AuthenticatedContractorDashboardRoute,
  AuthenticatedContractorSearchRoute: AuthenticatedContractorSearchRoute,
  AuthenticatedContractorVerificationRoute:
    AuthenticatedContractorVerificationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedGhlSetupRoute: AuthenticatedGhlSetupRoute,
  AuthenticatedMediaUploadRoute: AuthenticatedMediaUploadRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProposalsNewRoute: AuthenticatedProposalsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContractorApplyRoute: ContractorApplyRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SmsTermsRoute: SmsTermsRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WhyJobbidderRoute: WhyJobbidderRoute,
  AuditTokenRoute: AuditTokenRoute,
  EIdRoute: EIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GoSlugRoute: GoSlugRoute,
  PIdRoute: PIdRoute,
  ProposalIdRoute: ProposalIdRoute,
  ApiPublicAcceptProposalRoute: ApiPublicAcceptProposalRoute,
  ApiPublicContractorApplyRoute: ApiPublicContractorApplyRoute,
  ApiPublicContractorRecruitRoute: ApiPublicContractorRecruitRoute,
  ApiPublicCreateDepositInvoiceRoute: ApiPublicCreateDepositInvoiceRoute,
  ApiPublicDeclineProposalRoute: ApiPublicDeclineProposalRoute,
  ApiPublicDefaultContractorRoute: ApiPublicDefaultContractorRoute,
  ApiPublicIntakeSubmitRoute: ApiPublicIntakeSubmitRoute,
  ApiPublicProposalRoute: ApiPublicProposalRoute,
  ApiPublicProposalViewRoute: ApiPublicProposalViewRoute,
  ApiPublicSendProposalEmailRoute: ApiPublicSendProposalEmailRoute,
  ApiPublicTestEmailGhlRoute: ApiPublicTestEmailGhlRoute,
  ApiPublicTestProposalFlowRoute: ApiPublicTestProposalFlowRoute,
  ApiPublicTestSmsGhlRoute: ApiPublicTestSmsGhlRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksProcessFollowupsRoute: ApiPublicHooksProcessFollowupsRoute,
  ApiPublicHooksProcessJessicaFollowupsRoute:
    ApiPublicHooksProcessJessicaFollowupsRoute,
  ApiPublicWebhookGhlRoute: ApiPublicWebhookGhlRoute,
  ApiPublicWebhookGhlContractorSurveyRoute:
    ApiPublicWebhookGhlContractorSurveyRoute,
  ApiPublicWebhookGhlJessicaFollowupRoute:
    ApiPublicWebhookGhlJessicaFollowupRoute,
  ApiPublicWebhookGhlPaymentRoute: ApiPublicWebhookGhlPaymentRoute,
  ApiPublicWebhookGhlVoicePrequalRoute: ApiPublicWebhookGhlVoicePrequalRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
